name: gg_local_package_dependencies
description: gg_local_package_dependencies reads packages located in a local folder and creates a dependency graph.
version: 1.0.4
repository: https://github.com/inlavigo/gg_local_package_dependencies.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^1.1.12
  gg_console_colors: ^2.1.2
  gg_log: ^1.0.3
  gg_process: ^1.1.4
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3

dev_dependencies:
  gg_capture_print: ^1.0.6
  gg_install_gg: ^1.0.4
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0

executables:
 gg_local_package_dependencies: