name: gg_local_package_dependencies
description: gg_local_package_dependencies reads packages located in a local folder and creates a dependency graph.
version: 1.1.3
repository: https://github.com/inlavigo/gg_local_package_dependencies.git

environment:
  sdk: ">=3.8.1<4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^2.0.2
  gg_console_colors: ^2.1.2
  gg_log: ^1.0.3
  gg_process: ^1.1.4
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3

dev_dependencies:
  gg_capture_print: ^1.0.6
  lints: ^6.0.0
  test: ^1.24.0

executables:
  gg_local_package_dependencies:
